### ISSUE TITLE
ace-dynamic-card sample doesn't work on iOS

### ISSUE THREAD

**Issue by Mikhail2k15** [pnp/spfx-reference-scenarios#10]
**SVG** Images are not rendered on ios

**Comment by dcashpeterson** [comment]
@Mikhail2k15 I have noticed that in IOS as well mainly when you use them as a background image. I would post this as an issue in SPFx issues here https://github.com/SharePoint/sp-dev-docs/issues as this isn't related directly to something fixable by the sample author.

**Comment by Mikhail2k15** [comment]
@dcashpeterson Partially agree with that "this isn't related directly to something fixable by the sample author."  In my observation many of these sample has issues on Viva Connections Mobile inside Teams clients. I have several customers and partners that were inspired with these samples but in reality there are not functional on mobile. My suggestion is to have the checklist before another sample will go into these reference scenario repo. At the end of the day Viva Connecstions is positioning as a mobile first experience. 
This checklist might be something like this. 
- [ ] Teams iOS Viva Connections App
- [ ] Teams Android Viva Connections App 
- [ ] Teams Desktop for Windows Viva Connections App
- [ ] Teams Desktop for Mac Viva Connections App

**Comment by dcashpeterson** [comment]
Closed due to inactivity
