### ISSUE TITLE
ace-teams-covid - Missing Files Package from Sample Repo

### ISSUE THREAD

**Issue by kittykwok** [pnp/spfx-reference-scenarios#15]
Hi Team, 

I have downloaded the sample repo ace-teams-covid. and found that there might be missing folder in the repo.
There should be an organism folder in _src\webparts\covidAdmin_
![image](https://user-images.githubusercontent.com/83402391/158307310-d8831c92-3d3c-47b7-b82c-e3ed4199f50f.png)

However, i found the module is missing. Could you please help to check or did i miss nay config?
![image](https://user-images.githubusercontent.com/83402391/158307451-1839112a-f3df-490f-83e4-9408aa599f87.png)

Thanks all for your help!

**Comment by dcashpeterson** [comment]
@kittykwok thanks for reporting this. We will take a look at this.

**Comment by kittykwok** [comment]
@dcashpeterson thanks!
