### ISSUE TITLE
ace-teams-roomreservation documentation

### ISSUE THREAD

**Issue by pankajsurti** [pnp/spfx-reference-scenarios#33]
I was able to deploy the package on SPFX and Personal Teams Tab. I want to create a sample roomresconfig.json file.
 As per the following line 82 rr.service.ts file. I am not sure where do I add the JSON file. 
      this._currentConfig = await web.getFileByServerRelativeUrl(`/SiteAssets/${this.CONFIG_FOLDER}/${this.CONFIG_FILE_NAME}`).getJSON();

Which site's root site collection? As per the personal tab where is the site? I understand for the Teams Tab the Site is present.

+++++++++++++++++++++++++++++
This application uses demo data for the personal app that is stored in a JSON file in the root site collection Site Assets library in a folder called RoomReservation.
+++++++++++++++++++++++++++++

**Comment by dcashpeterson** [comment]
Closed and answered
