### ISSUE TITLE
Error Debugging - When I create a new Teams spfx application using Teams Toolkit

### ISSUE THREAD

**Issue by keedman4** [pnp/spfx-reference-scenarios#34]
When I create a new Teams spfx application using Teams Toolkit and debug I get errors below:

Error - sass - src\webparts\budget\components\Budget.module.scss(1,9): error Error: Can't find stylesheet to import.
  ╷
1 │ @import '~@fluentui/react/dist/sass/References.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\webparts\budget\components\Budget.module.scss 1:9  root stylesheet
[11:44:40] Error - 'sass' sub task errored after 234 ms 
 Can't find stylesheet to import.
  ╷
1 │ @import '~@fluentui/react/dist/sass/References.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\webparts\budget\components\Budget.module.scss 1:9  root stylesheet

**Comment by dcashpeterson** [comment]
@keedman4 I would suggest adding this error to the Teams Toolkit repo. I think that might get more eyes on it for you. 
https://github.com/OfficeDev/TeamsFx

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one.
