### ISSUE TITLE
Something went wrong - JSON error.

### ISSUE THREAD

**Issue by cibinjoe** [pnp/spfx-reference-scenarios#35]
While opening the tab technical error occurred - something went wrong and JSON error showing in console.
![Wrong](https://github.com/pnp/spfx-reference-scenarios/assets/102781044/06718c68-a976-45f4-bb64-513bb78c5c0d)
![Issue](https://github.com/pnp/spfx-reference-scenarios/assets/102781044/7a4e246b-bc61-4224-9b56-912be8f20462)

**Comment by dcashpeterson** [comment]
@cibinjoe What sample are you getting this error on?

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one.
